feat(STOCK-11) minor optimisation
vladdossik/lissa-trading-auth-service pull request #5
Opened 2024-08-21 19:25 UTC by Belaquaa

2024-08-22 04:45 UTC, vladdossik requested changes

2024-08-22 04:45 UTC, vladdossik commented on pom.xml
> +            <artifactId>platform-auth-lib</artifactId>
я уже говорил, что мы не можем использовать либу чужого проекта

2024-08-22 04:45 UTC, vladdossik commented on src/main/java/lissa/trading/auth/service/security/AuthenticationContextHolder.java
> +        private String telegramNickname;  // telegramNickname
нужен ли тут коммент

2024-08-24 05:28 UTC, vladdossik commented on src/main/java/lissa/trading/auth/service/config/CacheConfig.java
> +                .expireAfterWrite(5, TimeUnit.MINUTES)
мне кажется эти штуки должны быть быть вынесены в йамл (я про 5 и 100)

2024-08-24 05:28 UTC, vladdossik commented on src/main/java/lissa/trading/auth/service/details/CustomUserDetailsService.java
> +    @Cacheable(value = "users", key = "#telegramNickname")
telegram_nickname

2024-08-26 09:32 UTC, Belaquaa commented on src/main/java/lissa/trading/auth/service/details/CustomUserDetailsService.java
> +    @Cacheable(value = "users", key = "#telegramNickname")
А здесь точно так сделать?
Будет 
```
@Service
@RequiredArgsConstructor
public class CustomUserDetailsService implements UserDetailsService {

    private final UserRepository userRepository;

    @Override
    @Transactional
    @Cacheable(value = "users", key = "#telegram_nickname")
    public CustomUserDetails loadUserByUsername(String telegram_nickname) throws UsernameNotFoundException {
        User user = userRepository.findByTelegramNickname(telegram_nickname)
                .orElseThrow(() -> new UsernameNotFoundException("User not found with telegram nickname: " + telegram_nickname));

        return new CustomUserDetails(user);
    }
}
```

2024-08-26 09:32 UTC, Belaquaa commented on src/main/java/lissa/trading/auth/service/details/CustomUserDetailsService.java
> +    @Cacheable(value = "users", key = "#telegramNickname")
то есть все telegramNickname -> telegram_nickname

2024-08-26 12:12 UTC, vladdossik approved these changes

2024-08-26 12:52 UTC, merged